#!/bin/zsh
#=================================================
# name:   dirdiff.zsh
# author: Pawel Bogut <https://pbogut.me>
# date:   29/06/2018
#=================================================
dirdiff() {
  if [[ -z $2 ]]; then
    echo "Usage: dirdiff /path/to/dir/one /path/to/dir/two"
  else
    echo ":bw! | DirDiff $1 $2" | $(which $EDITOR) $TMP/skip_session
  fi
}
