#!/bin/bash
#=================================================
# name:   gst.zsh
# author: Pawel Bogut <https://pbogut.me>
# date:   18/12/2020
#=================================================
gst() {
  nvim . +XGst
}
