require('settings')
require('plugins')
require('autogroups')
require('keymappings')
require('commands')
require('helper')
-- local plugins --
require('projector')
require('plugins.projector')
require('remotesync')
