gui:
  scrollHeight: 2
  showBranchCommitHash: false
  scrollPastBottom: true
  screenMode: normal
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: true
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 4
  mainPanelSplitMode: flexible
  theme:
    lightTheme: false
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - blue
  commitLength:
    show: true
  skipNoStagedFilesWarning: false
  showFileTree: false
  showRandomTip: true
  showCommandLog: true
  commandLogSize: 8
git:
  paging:
    colorArg: always
    pager: diff-so-fancy
    # useConfig: false
  merging:
    manualCommit: false
    args: ""
  pull:
    mode: merge
  skipHookPrefix: WIP
  autoFetch: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
  overrideGpg: false
  disableForcePushing: false
  commitPrefixes: {}
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
update:
  method: prompt
  days: 14
refresher:
  refreshInterval: 10
  fetchInterval: 60
reporting: undetermined
splashUpdatesIndex: 0
confirmOnQuit: false
quitOnTopLevelReturn: false
keybinding:
  universal:
    quit: q
    quit-alt1: <c-c>
    return: <esc>
    quitWithoutChangingDirectory: Q
    togglePanel: <tab>
    prevItem: <up>
    nextItem: <down>
    prevItem-alt: k
    nextItem-alt: j
    prevPage: ','
    nextPage: .
    # gotoTop: <
    # gotoBottom: '>'
    gotoTop: g
    gotoBottom: G
    prevBlock: <left>
    nextBlock: <right>
    prevBlock-alt: h
    nextBlock-alt: l
    nextBlock-alt2: <tab>
    prevBlock-alt2: <backtab>
    nextMatch: "n"
    prevMatch: "N"
    startSearch: /
    optionMenu: x
    optionMenu-alt1: '?'
    select: <space>
    goInto: <enter>
    confirm: <enter>
    confirm-alt1: "y"
    remove: d
    new: "n"
    edit: e
    openFile: o
    scrollUpMain: <pgup>
    scrollDownMain: <pgdown>
    scrollUpMain-alt1: K
    scrollDownMain-alt1: J
    # scrollUpMain-alt2: <c-u>
    # scrollDownMain-alt2: <c-d>
    executeShellCommand: ':'
    createRebaseOptionsMenu: m
    pushFiles: P
    pullFiles: p
    refresh: R
    createPatchOptionsMenu: <c-p>
    nextTab: ']'
    prevTab: '['
    nextScreenMode: '-'
    prevScreenMode: '_'
    undo: z
    redo: <c-z>
    filteringMenu: <c-s>
    diffingMenu: W
    diffingMenu-alt: <c-e>
    copyToClipboard: <c-o>
    openRecentRepos: <c-r>
    submitEditorText: <enter>
    appendNewline: <a-enter>
    extrasMenu: '@'
  status:
    checkForUpdate: u
    recentRepos: <enter>
    allBranchesLogGraph: a
  files:
    scrollUp: <c-u>
    scrollDown: <c-d>
    commitChanges: c
    commitChangesWithoutHook: w
    amendLastCommit: A
    commitChangesWithEditor: ''
    ignoreFile: i
    refreshFiles: r
    stashAllChanges: s
    viewStashOptions: S
    toggleStagedAll: <c-o>
    viewResetOptions: D
    fetch: f
    toggleTreeView: '`'
    openMergeTool: M
  branches:
    createPullRequest: o
    copyPullRequestURL: <c-y>
    checkoutBranchByName: c
    forceCheckoutBranch: F
    rebaseBranch: b
    renameBranch: r
    mergeIntoCurrentBranch: M
    viewGitFlowOptions: i
    fastForward: f
    pushTag: P
    setUpstream: u
    fetchRemote: f
  commits:
    squashDown: s
    renameCommit: e
    editCommit: r
    renameCommitWithEditor: 'E'
    viewResetOptions: ''
    markCommitAsFixup: f
    createFixupCommit: F
    squashAboveCommits: S
    moveDownCommit: <c-j>
    moveUpCommit: <c-k>
    amendToCommit: A
    pickCommit: p
    revertCommit: t
    cherryPickCopy: c
    cherryPickCopyRange: V
    pasteCommits: v
    tagCommit: T
    checkoutCommit: <space>
    resetCherryPick: <c-R>
    copyCommitMessageToClipboard: <c-y>
  stash:
    popStash: ';'
  commitFiles:
    checkoutCommitFile: c
  main:
    toggleDragSelect: v
    toggleDragSelect-alt: V
    toggleSelectHunk: a
    pickBothHunks: b
  submodules:
    init: i
    update: u
    bulkMenu: b
os:
  open: '$TERMINAL -e nvim {{filename}}'
  openLink: xdg-open {{link}} >/dev/null 2>&1

disableStartupPopups: false
customCommands:
  - key: 'C'
    description: 'Commit changes with editor'
    context: 'global'
    command: 'git commit --verbose'
    output: terminal
  - key: <c-l>
    description: 'Commit changes with editor'
    context: 'global'
    command: 'git pullff'
    output: terminal
  - key: <c-r>
    description: 'Pull rebase'
    context: 'global'
    command: 'git pullrb'
    output: terminal
  - key: 'o'
    description: 'Open file'
    context: 'files'
    command: 'nvim {{ .SelectedFile.Name }}'
    output: terminal
  - key: 'o'
    description: 'Open file'
    context: 'staging'
    command: 'nvim {{ .SelectedFile.Name }}'
    output: terminal
  - key: 'p'
    description: 'Git ap'
    context: 'files'
    command: 'git ap {{ .SelectedFile.Name }}'
    output: terminal
# contexts: status, files, localBranches, remotes, remoteBranches,
#           tags, commits, reflogCommits, subCommits, commitFiles,
#           stash, normal, merging, patchBuilding, staging, menu,
#           credentials, confirmation, search, commitMessage,
#           submodules, suggestions, cmdLog
services: {}
notARepository: prompt
