#!/usr/bin/env bash
#=================================================
# name:   mpv
# author: Pawel Bogut <https://pbogut.me>
# date:   24/12/2021
#=================================================
# browser ":open $1"
echo "$QUTE_URL" | sed -E 's,https?://(www\.)?(.*?)/.*?\?(.*$),\3,' | (
    read -r query
    query=$(echo "$query" | sed -E 's,.*?q=([^&]*).*$,\1,')
    path=$(echo "$QUTE_URL" | sed -E 's,https?://(www\.)?([^/]+)/(.*$),\3,')
    domain=$(echo "$QUTE_URL" | sed -E 's,https?://(www\.)?([^/]+)/(.*$),\2,')

    # echo $domain
    case $domain in
        invidious.pbogut.me)
            domain="youtube.com"
            newurl="https://$domain/$path"
            # shellcheck disable=SC2001
            newurl=$(sed 's,&t=[0-9]*,,' <<< "$newurl")
            # shellcheck disable=SC2001
            newurl=$(sed 's,?t=[0-9]*&,?,' <<< "$newurl")
            # shellcheck disable=SC2001
            newurl=$(sed 's,?t=[0-9]*$,,' <<< "$newurl")

            splash youtube
            mpv "$newurl"
            ;;
        youtube.com | youtu.be)
            newurl="$QUTE_URL"
            # shellcheck disable=SC2001
            newurl=$(sed 's,&t=[0-9]*,,' <<< "$newurl")
            # shellcheck disable=SC2001
            newurl=$(sed 's,?t=[0-9]*&,?,' <<< "$newurl")
            # shellcheck disable=SC2001
            newurl=$(sed 's,?t=[0-9]*$,,' <<< "$newurl")

            splash youtube
            mpv "$newurl"
            ;;
        *)
            splash youtube
            mpv "$QUTE_URL"
            ;;
    esac
)
