#!/usr/bin/env bash
#=================================================
# name:   vaultwarden
# author: pbogut <pbogut@pbogut.me>
# date:   16/08/2024
#=================================================
usage() {
  echo "Ussage: ${0##*/} [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  -h, --help              display this help and exit"
  echo "      --open              open selected entry url"
  echo "      --login             type in user and password"
  echo "      --user              type in user"
  echo "      --pass              type in password"
  echo "      --totp              type in totp code"
  echo "      --create            create entry"
  echo "      --refresh-cache     type in totp code"
}

dir="$HOME/.config/passbolt"

__unlock() {
  if ! unlocked > /dev/null 2>&1; then
    rbw unlock
  fi
}
__dmenu() {
  if [[ -n "$WAYLAND_DISPLAY" ]]; then
    wofi --cache-file /dev/null --dmenu --search "$1"
  else
    rofi -dmenu -p -filter "$1"
  fi
}
__remove_url_prefix() {
    sed -E 's,^(accounts|dash|dashboard|online|app|login|panel|auth|system)\.,,' # remove common prefixes
}
__remove_url_suffix() {
    sed -E 's,\.(co\.uk|com\.net|com\...|..|...)$,,' # remove common suffixes
}
__create_entry() {
  file=$(mktemp -t vaultwarden.XXXXXX)
  domain=$(echo "$QUTE_URL" | awk -F'[/:]' '{print $4}')
  url=$(echo "$QUTE_URL" | awk -F'[/:]' '{print $1 "://" $4}')
  name=$(echo "$domain" | __remove_url_prefix | __remove_url_suffix)
  {
    echo "Name: ${name^}"
    echo "URL: $url"
    echo "Username: $(genmail "$name")"
    echo "Password: $(genpass)"
  } >> "$file"
  terminal-float nvim "$file"
  while read -r line; do
    if [[ $line == "Name: "* ]]; then
      name=${line##Name: }
    elif [[ $line == "URL: "* ]]; then
      uri=${line##URL: }
    elif [[ $line == "Username: "* ]]; then
      username=${line##Username: }
    elif [[ $line == "Password: "* ]]; then
      password=${line##Password: }
    fi
  done < "$file"
  if [[ -z "$name" ]] || [[ -z "$uri" ]] || [[ -z "$username" ]] || [[ -z "$password" ]]; then
    echo "Invalid input"
    exit 1
  fi
  env EDITOR=tee rbw add "$name" "$username" --uri "$uri" <<< "$password"

  at now <<< "${BASH_SOURCE[0]} --refresh-cache &"
}
__list_id_has_code() {
  rbw list --fields id | while read -r id; do
    code="$(rbw get -f code "$id")";
    if [[ $code != "" ]]; then
      echo "$id";
    fi;
  done
}
__list_raw_has_totp() {
  __list | grep -f <(__list_id_has_code)
}
__refresh_cache() {
  temp_file=$(mktemp)
  __list_raw_has_totp > "$temp_file"
  mv "$temp_file" "$dir/resources-totp.txt"
  rbw sync
}
__list() {
  rbw list --fields id,name,user,uris  | column -s $'\t' -t -o' | '
}
__list_has_totp() {
  mkdir -p "$dir"
  if [[ -f "$dir/resources-totp.txt" ]]; then
    cat "$dir/resources-totp.txt"
  else
    __list_raw_has_totp
  fi
  at now <<< "${BASH_SOURCE[0]} --refresh-cache &"
}
__select_id() {
  __list | __dmenu | awk '{print $1}'
}
__url() {
  echo "$QUTE_URL" |
    sed 's,^[a-z]*://\([^/]*\).*,\1,' | # remove scheme
    __remove_url_prefix
}
__select_id_with_search() {
    __list | __dmenu "$(__url)" | awk '{print $1}'
}
__select_id_with_search_has_totp() {
    __list_has_totp | __dmenu "$(__url)" | awk '{print $1}'
}
__qb_type() {
  echo "fake-key $1" >> "$QUTE_FIFO"
}
__qb_open() {
  resource="$1"
  uri=$(echo "$resource" | jq -r '.login.uris[0].uri')
  echo "open $uri" >> "$QUTE_FIFO"
}
__qb_login() {
  id="$1"
  user=$(rbw get -f user "$id")
  pass=$(rbw get -f password "$id")
  login_instruction=$(rbw get --field LOGIN "$id")
  if [[ $login_instruction == "" ]]; then
      __qb_type "$user"
      __qb_type "<tab>"
      __qb_type "$pass"
  else
    echo "$login_instruction"
    echo "$login_instruction" \
    | sed 's,^LOGIN:,,' \
    | sed "s,:,\n,g" \
    | while read -r line; do
      if [[ $line == "<pass>" ]]; then
        __qb_type "$pass";
      elif [[ $line == "<user>" ]]; then
        __qb_type "$user";
      else
        __qb_type "$line";
      fi
    done
  fi
}

if test $# -eq 0; then
  usage
  exit 0
fi
while test $# -gt 0; do
  case "$1" in
    --open)
      __unlock
      id=$(__select_id)
      if [[ $id == "" ]]; then
        exit 0
      fi
      uri="$(__list | grep "^$id" | cut -d'|' -f4)"
      echo "open $uri" >> "$QUTE_FIFO"
      #__qb_open "$resource"
      exit 0
      ;;
    --login)
      __unlock
      id=$(__select_id_with_search)
      if [[ $id == "" ]]; then
        exit 0
      fi
      __qb_login "$id"
      exit 0
      ;;
    --user)
      __unlock
      id=$(__select_id_with_search)
      if [[ $id == "" ]]; then
        exit 1
      fi
      user=$(rbw get -f user "$id")
      __qb_type "$user"
      exit 0
      ;;
    --pass)
      __unlock
      id=$(__select_id_with_search)
      if [[ $id == "" ]]; then
        exit 1
      fi
      pass=$(rbw get -f password "$id")
      __qb_type "$pass"
      exit 0
      ;;
    --totp)
      __unlock
      id=$(__select_id_with_search_has_totp)
      if [[ $id == "" ]]; then
        exit 1
      fi
      totp=$(rbw get -f code "$id")
      __qb_type "$totp"
      exit 0
      ;;
    --create)
      __unlock
      __create_entry
      exit 0
      ;;
    --refresh-cache)
      __unlock
      __refresh_cache
      exit 0
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done
