call local#paranoicbackup#init()
call local#changepaste#init()
call local#wipeout#init()
call local#combineselection#init()
call local#repl#init()
call local#logwatch#init()
call local#setlocal#init()
call local#openscad#init()
