#!/bin/bash
#=================================================
# name:   vimwiki.zsh
# author: Pawel Bogut <pbogut@ukpos.com> <http://pbogut.me>
# date:   24/05/2017
#=================================================
wiki() {
    mkdir -p "$HOME/Wiki"
    cd "$HOME/Wiki" || exit
    nvim ./index.md
    cd - || exit
}
