#!/bin/bash
#=================================================
# name:   archive
# author: Pawel Bogut <https://pbogut.me>
# date:   09/12/2020
#=================================================
hostname=$(hostname)
if [[ $hostname != "redeye" ]]; then
    # only archive on a main PC
    exit 0
fi
daysago=1095
todate=$(date --date="$daysago days ago" '+%Y-%m-%d')
search="date:..$todate"
account_filter=${1:-.}

echo ""
echo " > archive $search in $account_filter"

notmuch search --output files $search | grep $account_filter | grep -v '\.archive' |
    while read line; do
        origdir=$(dirname $line)
        archdir=$(echo $origdir | sed 's#Maildir/\(.*\)/\(.*\)/\(cur\|new\)#Maildir/\1/\2.archive/\3#')
        filename=$(basename $line)

        mkdir -p $archdir

        if [[ "$origdir" == "$archdir" ]]; then
            # already archived
            continue
        fi

        if [[ ! -f "$origdir/$filename" ]]; then
            # file do not exist
            continue
        fi

        echo "$filename:"
        echo "    move $origdir" '->' "$archdir"
        mv "$origdir/$filename" "$archdir/$filename" > /dev/null 2>&1
    done

find $HOME/Maildir -iname '*.archive' -type d | while read source; do
    dest=$HOME/.Maildir-megasync${source##$HOME/Maildir}
    destdir=$(dirname $dest)
    mkdir -p $destdir
    mv $source $dest
    ln -s $dest $source
done
