#!/bin/bash
#=================================================
# name:   archive
# author: Pawel Bogut <https://pbogut.me>
# date:   09/12/2020
#=================================================
hostname=$(hostname)
if [[ $hostname != "redeye" ]]; then
    # only archive on a main PC
    exit 0
fi
daysago=1095
todate=$(date --date="$daysago days ago" '+%Y-%m-%d')
search="date:..$todate"
account=$1
account_filter="/Maildir/${account:-.}/"

echo ""
echo " > archive $search in $account_filter"

notmuch search --output files $search and folder:/^$account/ and not folder:/\.archive/ |
    while read line; do
        origdir=$(dirname $line)
        archdir=$(echo $origdir | sed 's#Maildir/\(.*\)/\(.*\)/\(cur\|new\)#Maildir/\1/\2.archive/\3#')
        filename=$(basename $line)

        mkdir -p $archdir

        if [[ "$origdir" == "$archdir" ]]; then
            # already archived
            continue
        fi

        if [[ ! -f "$origdir/$filename" ]]; then
            # file do not exist
            continue
        fi

        echo "$filename:"
        echo "    move $origdir" '->' "$archdir"
        mv "$origdir/$filename" "$archdir/$filename" > /dev/null 2>&1
    done

find $HOME/Maildir -iname '*.archive' -type d | while read source; do
    dest=/storage/nextcloud/Maildir.archive${source##$HOME/Maildir}
    destdir=$(dirname $dest)
    mkdir -p $destdir
    mv $source $dest
    ln -s $dest $source
done

if [[ $account == "gmail" ]]; then
  gmaildaysago=$(expr $daysago + 3)
  gmailtodate=$(date --date="$gmaildaysago days ago" '+%Y/%m/%d')
  echo ""
  echo "To delete files from gmail use this query in web mail: "
  echo before:$gmailtodate
fi
