#!/bin/bash
hostname=`hostname`
begin_hook="$HOME/.offlineimap-hooks-pre-postsync-$hostname.sh"
[[ -f $begin_hook ]] && $begin_hook

notmuch new
# add image tag
notmuch tag +image -- tag:new and mimetype:image
notmuch tag +attachment -- tag:new and attachment
# set up account tag
notmuch search --output=threads tag:new | while read thread; do
    notmuch search --output=files $thread | grep -v 'Maildir/sent' | sed 's#.*Maildir/\([^/]*\)/.*#+account-\1#' | while read account; do
        notmuch tag $account -- $thread
    done
done
# tag github messages
notmuch search --output=files from:notifications@github.com and tag:new | while read f; do
    tag=`cat "$f" | grep '^To: ' | sed 's/^To: \([^ ]*\).*/\1/g' | sed 's/^"\(.*\)"$/\1/'`
    id=`cat "$f" | grep '^Message-ID: ' | sed 's/^Message-ID: <\([^ ]*\)>.*/\1/g'`
    notmuch tag +github/$tag -- id:$id
    # notmuch tag -inbox +github/$tag -- id:$id
done
# tag gitlab messages (try to figure how to tag them by project @see github)
notmuch tag +gitlab -- tag:new and from:gitlab@mg.gitlab.com
# tag jira messages
notmuch tag +jira -- "tag:new and from:jira@assuredpharmacy.atlassian.net"
notmuch tag -inbox -- "(tag:jira and tag:inbox) and not tag:unread"

# emails from myself
notmuch tag -new -inbox -unread +sent -- from:"Pawel Bogut" and tag:new
notmuch tag -new -inbox -unread +sent -- from:"Paweł Bogut" and tag:new
# todoist tasks
notmuch tag -new -inbox -unread +archive -- to:add.task%todoist.net and tag:new

# tags as directories
# im removing new tag so I can set everything
# before archive, which in gmails contain all mails by default (fy Google)
ls -1d --color=never ~/Maildir/*/INBOX | sed "s#$HOME/Maildir/#folder:#g" | xargs notmuch tag -new +inbox -- tag:new and
ls -1d --color=never ~/Maildir/*/drafts | sed "s#$HOME/Maildir/#folder:#g" | xargs notmuch tag -new +drafts +draft -- tag:new and
ls -1d --color=never ~/Maildir/*/sent | sed "s#$HOME/Maildir/#folder:#g" | xargs notmuch tag -new +sent -- tag:new and
ls -1d --color=never ~/Maildir/*/trash | sed "s#$HOME/Maildir/#folder:#g" | xargs notmuch tag -new +trash -- tag:new and
ls -1d --color=never ~/Maildir/*/spam | sed "s#$HOME/Maildir/#folder:#g" | xargs notmuch tag -new +spamish -- tag:new and
# in gmail everything is in archive, so we do this at the end
ls -1d --color=never ~/Maildir/*/archive | sed "s#$HOME/Maildir/#folder:#g" | xargs notmuch tag -new +archive -- tag:new and

# add senders to abook
# notmuch search --output=files tag:new | while read l; do cat "$l" | abook --add-email-quiet; done
# remove duplicates
# ~/.scripts/abook-remove-duplicates.sh

# auto archivie couses issues with gmail - wrrrr....
#notmuch tag +archive -- date:..`date --date='6 month ago' +%Y-%m-%d`
notmuch tag -new -- tag:new #clear new tag

# Thread view - Add sent items to inbox if part of the thread is in inbox
notmuch tag +inbox -- tag:inbox $(echo $(notmuch search tag:inbox | awk '{print "or " $1}'))

end_hook="$HOME/.offlineimap-hooks-post-postsync-$hostname.sh"
[[ -f $end_hook ]] && $end_hook
