#!/bin/bash
#=================================================
# name:   open
# author: Pawel Bogut <pbogut@ukpos.com> <http://pbogut.me>
# date:   01/03/2017
#=================================================
usage() {
  echo "Ussage: ${0##*/} [OPTIONS] <FILE(s)>"
  echo ""
  echo "Options:"
  echo "  -h, --help     display this help and exit"
  echo "  -a, --app      app to open file with"
}

app="select"
files=()

if [[ -z $1 ]]; then
  usage
  exit 1
fi

while test $# -gt 0; do
  case "$1" in
    --help|-h)
      usage
      exit 0
      ;;
    --app|-a)
      app=$2
      shift
      shift
      ;;
    *)
      files+=("$1")
      shift
      ;;
  esac
done

if [[ $app = "select" ]] && [[ $(/usr/bin/rifle -l "$1" | wc -l) -gt 1 ]]; then
  /usr/bin/rifle -l "${files[@]}" |
    wofi --dmenu -p "App:" --cache-file /dev/null |
    sed 's/\([0-9]*\).*/\1/' |
    (
      read -r choice
      [[ $choice != "" ]] && $TERMINAL -e /usr/bin/rifle "${files[@]}" -p "$choice"
    )
else
  /usr/bin/rifle "${files[@]}" -p "$app"
fi
