#!/bin/bash
#=================================================
# name:   qutebrowser_ukpos.sh
# author: Pawel Bogut <http://pbogut.me>
# date:   16/01/2017
#=================================================
echo "$@" >/tmp/last_url-$USER
display=${DISPLAY:-:0}

if [[ $1 =~ ^https://appear.in/ || $1 =~ url=https%3A%2F%2Fappear.in%2F ]] \
  ; then
  chromium --app="$1" "${@:2}"
elif [[ $1 =~ ^http://chromecast.smplayer.info/ ]]; then
  google-chrome-stable --app="$1" "${@:2}"
else
  DISPLAY=$display qutebrowser --target window --backend webengine --enable-webengine-inspector "$@"
fi
