#!/bin/bash
#=================================================
# name:   compose
# author: Pawel Bogut <http://pbogut.me>
# date:   11/06/2017
#=================================================
docker-compose "$@"
