#!/bin/bash
#=================================================
# name:   config
# author: Pawel Bogut <https://pbogut.me>
# date:   15/12/2020
#=================================================
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
$dir/config.rb "$@"
