#!/bin/bash
#=================================================
# name:   docnet.sh
# author: Pawel Bogut <pbogut@ukpos.com> <http://pbogut.me>
# date:   18/05/2017
#=================================================
dnsip=$(ifconfig docker0 | awk '/inet /{print $2}')

echo ""
echo "Run your docker images with "'`'"--dns=$dnsip"'`'" flag"
echo ""

hosts="/tmp/docnet.hosts/"

mkdir -p $hosts
sudo killall -9 dnsmasq > /dev/null 2>&1
(sudo dnsmasq --hostsdir=$hosts -d --cache-size=0) > /dev/null 2>&1 &

docker events | while read line; do
  echo $line | grep 'network \(connect\|disconnect\)' | sed 's,.*network \(disconnect\|connect\).*container=\([0-9a-z]*\)\,.*,\1 \2,' | (read action hash
    if [[ $action == "connect" ]]; then
      inspect=$(docker inspect $hash)
      host=$(echo $inspect | jq '.[0].Config.Hostname' -r)
      ip=$(echo $inspect | jq '.[0].NetworkSettings.IPAddress' -r)
      if [[ $ip == "" ]]; then
        ip=$(echo $inspect |jq '.[0].NetworkSettings.Networks | map(.IPAddress) | first' -r)
      fi
      echo $ip $host | tee /tmp/docnet.hosts/$hash
    elif [[ $action == "disconnect" ]]; then
      echo disconnected $(echo $hash |sed 's,^\(.\{12\}\).*,\1,')
      rm /tmp/docnet.hosts/$hash
    fi
    sudo killall -s SIGHUP dnsmasq
  )
done


