#!/usr/bin/env bash
#=================================================
# name:   git-prune-worktree
# author: Pawel Bogut <https://pbogut.me>
# date:   18/08/2022
#=================================================
master="$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')"
branches=$(git branch --merged "$master" | grep -v "^\*" | grep '^\+' | sed 's/^\+ /  /')

if [[ -n $branches ]]; then
  echo "Worktrees merged with $master:"
  echo "$branches"
  echo "^ Branches above will be removed ^"
  read -p "Continue? [y/n] " -r confirm

  if [[ $confirm == "y" ]]; then
    while read -r branch; do
      git worktree remove "$branch"
    done <<< "$branches"
  fi
fi
