#!/bin/bash
#=================================================
# name:   i3-open
# author: Pawel Bogut <pbogut@ukpos.com> <http://pbogut.me>
# date:   01/03/2017
#=================================================

echo "$@" > /tmp/deb

if [[ -z $2 ]] && [[ `/usr/bin/rifle -l "$1" | wc -l` -gt 1 ]]; then
  /usr/bin/rifle -l "$1" | rofi -dmenu -p "App:" | sed 's/\([0-9]*\).*/\1/' | (read choice
    [[ $choice != "" ]] && $TERMINAL -e /usr/bin/rifle "$1" -p $choice)
else
/usr/bin/rifle "$@"
fi
