#!/bin/bash
#=================================================
# name:   keepass
# author: Pawel Bogut <https://pbogut.me>
# date:   17/05/2018
#=================================================
db="$KEEPASS_DB"
pass=$(gpg-config get keepass-pass)
if [[ $# -gt 1 ]]; then
    for last; do true; done
fi
if [[ $# -gt 2 ]]; then
    params=${@:2:$#-2}
fi

if [[ $1 == 'gui' ]]; then
    echo $pass | keepassxc --pw-stdin $db
    exit $?
fi
if [[ $1 == 'new' ]]; then
    temp=$(mktemp)
    echo "Name: $2" >$temp
    echo "URL: $3" >>$temp
    echo "UserName: $(gpg-config get default-email)" >>$temp
    #echo "Password: $(apg -m16 -n1 -MSNCL)" >>$temp
    vim $temp
    name=$(grep '^Name: ' $temp | sed 's,^Name: ,,')
    url=$(grep '^URL: ' $temp | sed 's,^URL: ,,')
    user=$(grep '^UserName: ' $temp | sed 's,^UserName: ,,')
    #npass=$(grep '^Password: ' $temp | sed 's,^Password: ,,')
    if [[ -z $name ]]; then
        exit 1
    else

        (
            echo $pass
        ) | keepassxc-cli add -g -u "$user" --url "$url" $db "$name" | tail -n +3
        exit 0
    fi
fi

if [[ $1 == 'change' ]]; then
    temp=$(mktemp)".keepass"
    $0 show "$2" | grep -v '^Notes' >$temp
    vim $temp
    name=$(grep '^Title: ' $temp | sed 's,^Title: ,,')
    url=$(grep '^URL: ' $temp | sed 's,^URL: ,,')
    user=$(grep '^UserName: ' $temp | sed 's,^UserName: ,,')
    npass=$(grep '^Password: ' $temp | sed 's,^Password: ,,')
    if [[ -z $name ]] || [[ -z $npass ]]; then
        exit 1
    else

        (
            echo $pass
            echo $npass
        ) | keepassxc-cli edit -p -u "$user" --url "$url" $db "$name" | tail -n +3
        exit 0
    fi
fi

echo keepassxc-cli $1 $params $db $last >/dev/stderr
if [[ -z $last ]]; then
    if [[ -z $params ]]; then
        echo $pass | keepassxc-cli $1 "$db" | tail -n +2
    else
        echo $pass | keepassxc-cli $1 "$params" "$db" | tail -n +2
    fi
else
    if [[ -z $params ]]; then
        echo $pass | keepassxc-cli $1 "$db" "$last" | tail -n +2
    else
        echo $pass | keepassxc-cli $1 "$params" "$db" "$last" | tail -n +2
    fi
fi
