#!/bin/bash
#=================================================
# name:   ls-project
# author: Pawel Bogut <pbogut@ukpos.com> <http://pbogut.me>
# date:   09/06/2017
#=================================================

find ~/projects -maxdepth 5 -mindepth 3 -printf "%T+\t%p\n" -type d |
    grep '\.git$\|CVS$\|\.svn$' |
    sort -r |
    sed 's,.*\t'"$HOME"'/projects/,,g' |
    sed 's,\(.*\)/\(\.git\|CVS\|\.svn\)$,\1,'

