#!/usr/bin/env bash
#=================================================
# name:   tmux-project
# author: author <author_contact>
# date:   26/04/2023
#=================================================
project=false
if [[ $TERM == "dumb" ]]; then
    project=$(ls-project | rofi -dmenu -q "$1")
else
    project=$(ls-project | fzf -q "$1")
fi

if [[ ! $project == "" ]]; then
  cd "$HOME/Projects/$project" || exit
  if [[ -f .git || -d .git ]]; then
      touch .git > /dev/null 2>&1
  else
      touch . > /dev/null 2>&1
  fi
    if [[ $TERM == "dumb" ]]; then
      alacritty -e tmux-vim
    else
      tmux-vim
    fi
fi
