#!/usr/bin/env bash
#=================================================
# name:   secret
# author: author <author_contact>
# date:   06/03/2024
#=================================================
key='"'"${1//\//'"."'}"'"'
jq -c -r ".$key // "'""' "$HOME/.secrets.json"
