#!/usr/bin/env bash
#=================================================
# name:   onshape
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   22/07/2025
#=================================================
swaymsg '[app_id="chrome-192.168.1.112__-Default"] focus' ||
    chromium --app=http://192.168.1.112:81 --profile-directory=Default
