#!/usr/bin/env bash
#=================================================
# name:   scuf-envision
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   11/01/2025
#=================================================

while :; do
    #killall -9 xboxdrv

    SCUF=$(ls /dev/input/by-id/*Scuf*event-joystick 2> /dev/null)
    if [ -z "$SCUF" ]; then
        echo "Scuf not found"
        sleep 3
        continue
    fi

    xboxdrv -c ~/.config/xboxdrv/scuf-envision.conf --mimic-xpad --axismap -y1=y1 --axismap -y2=y2 \
        --evdev "$SCUF" \
        --silent
done
