#!/usr/bin/env bash
#=================================================
# name:   onshape
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   22/07/2025
#=================================================
focus-or-exec "chrome-192.168.1.112__.*" \
    chromium --app=http://192.168.1.112:81 --profile-directory=Default
