#!/usr/bin/env bash
#=================================================
# name:   oldbox
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   17/08/2026
#=================================================
chromium --app=http://oldbox.local --profile-directory=Default
