#!/usr/bin/env bash
#=================================================
# name:   hypr-backandforth
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   27/10/2025
#
# based on script by adamnejm <adamnejm@gmail.com>
#=================================================
active_workspace="$(hyprctl activewindow -j | jq -r ".workspace.id")"
if [ "$active_workspace" = "null" ]; then exit; fi
previous_client="$(hyprctl clients -j | jq -r '[.[] | select(.workspace.id == '"$active_workspace"')] | sort_by(.focusHistoryID) | nth(1) | .address')"
if [ "$previous_client" = "null" ]; then exit; fi

hyprctl --batch \
  "dispatch focuswindow address:$previous_client; dispatch layoutmsg swapwithmaster ignoremaster"
