#!/usr/bin/env bash
status=0
if [[ ${HERDR_ENV:-} == 1 ]]; then
  herdr-project-layout dev
  status=$?
elif [[ -f ./Makefile ]]; then
  make dev
  status=$?
fi
read -r -p "Press enter to exit"
exit "$status"
