#!/usr/bin/env bash
#=================================================
# name:   chromium-start
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   17/08/2024
#=================================================
chromium --user-data-dir="$HOME/.config/chromium-work/" --class=chromium-work --profile-directory=Work "$@"
