#!/bin/bash
#=================================================
# name:   nvimdiff
# author: Pawel Bogut <https://pbogut.me>
# date:   23/12/2018
#=================================================
nvim -d $@
