#!/bin/bash
(while :; do
  inotifywait -e close_write /home/pbogut/.config/waybar/*
  killall waybar -USR2
done) &
loop_pid=$!

cleanup() {
  kill $loop_pid
}

trap cleanup SIGTERM SIGINT

while :; do
  waybar \
    --config "$HOME/.config/waybar/hypr.config" \
    --style "$HOME/.config/waybar/hypr.style.css"
  sleep 1s
done
