#!/usr/bin/env bash
#=================================================
# name:   firefox-work
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   21/09/2024
#=================================================
firefox-developer-edition --name firefox-work -p Work "$@"
