#!/usr/bin/env bash
#=================================================
# name:   terminal-float
# author: author <author_contact>
# date:   27/04/2024
#=================================================
terminal --float "$@"
