#!/usr/bin/env bash
#=================================================
# name:   theme-switch
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   24/10/2025
#=================================================
theme=$(ls -1 ~/.config/themes/ | grep -v '\(current\)' | fuzzel --dmenu --prompt="Select theme: ")

update_waybar_modules() {
  themepath="$HOME/.config/themes/current/waybar.css"
  icon=$(grep '^@define-color icon #' < "$themepath" | sed -E 's/^@define-color icon (#.*);$/\1/')
  important=$(grep '^@define-color important #' < "$themepath"| sed -E 's/^@define-color important (#.*);$/\1/')
  WAYBAR_ICON_COLOR="$icon" WAYBAR_IMPORTANT_COLOR="$important" chezmoi apply ~/.config/waybar/modules.jsonc
  echo WAYBAR_ICON_COLOR="$icon" WAYBAR_IMPORTANT_COLOR="$important"
}

if [[ -n $theme ]]; then
  ln -nsf "$HOME/.config/themes/$theme" "$HOME/.config/themes/current"
  update_waybar_modules
  killall waybar -USR2
  hyprctl -q reload
  touch ~/.config/alacritty/alacritty.toml
  tmux source-file ~/.config/tmux/tmux.conf 2>/dev/null
  dunstctl reload
fi
