#!/usr/bin/env bash
#=================================================
# name:   shadowplay
# author: Pawel Bogut <https://pbogut.me>
# date:   01/05/2026
# desc:   shadow play script - records gameplay
#         in background and saves clips on demand
#=================================================

record_minutes=300
record_fps=60
terminate="$TMPDIR/shadowplay.terminate"

usage() {
  echo "Ussage: ${0##*/} [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  -h, --help              display this help and exit"
  echo "  --fullscreen {monitor}  start recording whole monitor"
  echo "  --save                  save replay to file"
  echo "  --kill                  kill screen recording"
}

action=""
while test $# -gt 0; do
  case "$1" in
  --kill)
    action="kill"
    shift
    ;;
  --save | -s)
    action="save"
    shift
    ;;
  --record-time|--record-time=*|-r)
    if [[ $1 =~ --[a-z\-]+= ]]; then
      _val="${1//--time=/}"
      shift
    else
      _val="$2"
      shift; shift
    fi
    record_minutes="$_val"
    ;;
  --fullscreen | -f)
    action="fullscreen"
    shift
    screen="$1"
    shift
    ;;
  --help | -h)
    usage
    exit 0
    ;;
  *)
    usage
    exit 1
    ;;
  esac
done

_prams_audio() {
    audio=()
    gpu-screen-recorder --list-audio-devices | grep -q VR_P10
    vrp10=$?
    gpu-screen-recorder --list-audio-devices | grep -q Arctis_Pro_Wireless
    arctispro=$?
    gpu-screen-recorder --list-audio-devices | grep -q  'Easy Effects'
    easyeffects=$?
    if [[ $easyeffects -eq 0 ]]; then
        audio+=(-a "easyeffects_sink.monitor|easyeffects_source")
        audio+=(-a "easyeffects_sink.monitor")
        audio+=(-a "easyeffects_source")
    elif [[ $arctispro -eq 0 ]] && [[ $vrp10 -eq 0 ]]; then
        audio+=(-a "default_output|alsa_input.usb-SteelSeries_Arctis_Pro_Wireless-00.mono-fallback|alsa_input.usb-Telink_VR_P10_Dongle-00.mono-fallback")
        audio+=(-a "default_output")
        audio+=(-a "alsa_input.usb-SteelSeries_Arctis_Pro_Wireless-00.mono-fallback")
        audio+=(-a "alsa_input.usb-Telink_VR_P10_Dongle-00.mono-fallback")
    elif [[ $arctispro -eq 0 ]]; then
        audio+=(-a "default_output|alsa_input.usb-SteelSeries_Arctis_Pro_Wireless-00.mono-fallback")
        audio+=(-a "default_output")
        audio+=(-a "alsa_input.usb-SteelSeries_Arctis_Pro_Wireless-00.mono-fallback")
    elif [[ $vrp10 -eq 0 ]]; then
        audio+=(-a "default_output|alsa_input.usb-Telink_VR_P10_Dongle-00.mono-fallback")
        audio+=(-a "default_output")
        audio+=(-a "alsa_input.usb-Telink_VR_P10_Dongle-00.mono-fallback")
    fi
}

if [[ -z $action ]]; then
  usage
  exit 1
fi

if [[ $action == "kill" ]]; then
  pkill -TERM -f gpu-screen-recorder
  touch "$terminate"
fi

if [[ $action == "save" ]]; then
  if pkill -USR1 -f gpu-screen-recorder; then
    notify-send -u low "Saving replay..."
  else
    notify-send -u critical "No screen recording running"
  fi
fi

if [[ $action == "fullscreen" ]]; then
  if [[ -z $screen ]]; then
    usage
    exit 1
  fi
  rm "$terminate" > /dev/null 2>&1 || true
  pkill -TERM -f gpu-screen-recorder
  count=0
  while :; do
    count=$(( count + 1 ))
    notify-send -u low "Start Shadowing $screen"

    path="$HOME/Videos/ShadowPlay"

    mkdir -p "$path"

      # shellcheck disable=SC2046
      gpu-screen-recorder $(_prams_audio) \
        -w "$screen" \
        -c mp4 -f $record_fps \
        -a "$(pactl get-default-sink).monitor" \
        -r $record_minutes \
        -o "$path" | while read -r line; do
      if [[ $line == "$path"* ]]; then
        notify-send -u low "Saved replay to $line"
      fi
    done

    if [[ -f "$terminate" ]]; then
      rm "$terminate"
      exit 0
    fi
    if [[ $count -gt 100 ]] ;then
      exit 1
    fi
  done
fi
