#!/bin/bash
#=================================================
# name:   qutebrowser_ukpos.sh
# author: Pawel Bogut <http://pbogut.me>
# date:   16/01/2017
#=================================================
export PATH="$PATH:/home/$USER/.bin"
export PATH="$PATH:/home/$USER/.scripts"

url="$1"

if [[ "$1" == '--work' ]]; then
  shift
  vivaldi-work "$@" &
elif [[ $url =~ ^https://invidious\.pbogut\.me/watch\?v= ]]; then
  shift
  youtube "$url" "${@//\[\[AMPERSAND\]\]/&}" &
elif [[ $url =~ ^https://www\.youtube\.com/watch\?v= ]]; then
  shift
  youtube "$url" "${@//\[\[AMPERSAND\]\]/&}" &
elif [[ $url =~ ^https://open\.spotify\.com ]]; then
  vivaldi-personal "$@" &
elif [[ $url =~ ^https://.*\.zoom\.us ]]; then
  shift
  chromium --app="$url" --profile-directory=Default "$@" &
elif [[ $url =~ ^https://teams\.microsoft\.com ]]; then
  shift
  chromium --app="$url" --profile-directory=Default "$@" &
elif [[ $url =~ ^https://.*\.richpanel\.com ]]; then
  vivaldi-work "$@" &
elif [[ $url =~ ^https://gitlab\.com ]]; then
  vivaldi-work "$@" &
elif [[ $url =~ ^https://local\.* ]]; then
  vivaldi-work "$@" &
elif [[ $url =~ ^https?://*\.local ]]; then
  vivaldi-work "$@" &
else
  vivaldi-personal "$@" &
fi

exit 0;
