#!/usr/bin/env bash
#=================================================
# name:   zen-personal
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   11/02/2025
#=================================================
zen-browser --name zen-personal -p Personal "$@"
