#!/usr/bin/env bash
#=================================================
# name:   focus-or-exec
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   04/11/2025
#=================================================


usage() {
    echo "Ussage: ${0##*/} [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -h, --help     display this help and exit"
}
mode="class"
while test $# -gt 0; do
    case "$1" in
        --help|-h)
            usage
            exit 0
            ;;
        --title|-t)
            mode="title"
            shift
            ;;
        *)
            class=$1
            shift
            break
            ;;
    esac
done

if [[ $mode == "class" ]]; then
    if [[ $XDG_CURRENT_DESKTOP == "niri" ]]; then
        window_id=$(niri msg -j windows | jq --arg class "$class" '.[] | select(.app_id == $class) | .id' | head -n1)
        if [[ -z $window_id ]]; then
            window_id=$(niri msg -j windows | jq --arg class "$class" '.[] | select(.app_id | test($class)) | .id' | head -n1)
        fi
        if [[ -n $window_id ]]; then
            niri msg action focus-window --id "$window_id"
        else
            exec "$@"
        fi
    elif [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
        hypr-focusorexec "$class" "$@"
    elif [[ $XDG_CURRENT_DESKTOP == "sway" ]]; then
        swaymsg '[app_id="'"$class"'"] focus' ||
            swaymsg '[class="'"$class"'"] focus' ||
            exec "$@"
    fi
fi
if [[ $mode == "title" ]]; then
    if [[ $XDG_CURRENT_DESKTOP == "niri" ]]; then
        window_id=$(niri msg -j windows | jq --arg class "$class" '.[] | select(.title == $class) | .id' | head -n1)
        if [[ -z $window_id ]]; then
            window_id=$(niri msg -j windows | jq --arg class "$class" '.[] | select(.title | test($class)) | .id' | head -n1)
        fi
        if [[ -n $window_id ]]; then
            niri msg action focus-window --id "$window_id"
        else
            exec "$@"
        fi
    elif [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
        hypr-focusorexec "$class" "$@"
    elif [[ $XDG_CURRENT_DESKTOP == "sway" ]]; then
        swaymsg '[title="'"$class"'"] focus' ||
            swaymsg '[title="'"$class"'"] focus' ||
            exec "$@"
    fi
fi
