#!/usr/bin/env bash
#=================================================
# name:   hypr-togglemfact
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   21/10/2025
#=================================================
mkdir /tmp/ws-mfact-toggle -p
workspace=$(hyprctl activeworkspace -j | jq .name -r)
touch "/tmp/ws-mfact-toggle/$workspace"
current="$(cat "/tmp/ws-mfact-toggle/$workspace")"

new=0.80 # default is 0.65, so first use should be 0.80
if [[ $current == "0.5" ]]; then
  new=0.65;
fi
if [[ $current == "0.65" ]]; then
  new=0.80;
fi
if [[ $current == "0.80" ]]; then
  new=0.5;
fi

hyprctl -q dispatch layoutmsg mfact exact "$new"
echo "$new" > "/tmp/ws-mfact-toggle/$workspace"
