#!/usr/bin/env bash
#=================================================
# name:   aoc-menu
# author: pbogut <pbogut@pbogut.me>
# date:   31/03/2024
#=================================================

usage() {
  echo "Ussage: ${0##*/} [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  -d, --display  display number"
  echo "  -h, --help     display this help and exit"
}

display=0

while test $# -gt 0; do
  case "$1" in
    gamemode)
      # DC
      shift
      if [ -z "$1" ]; then
        current=$(ddcutil getvcp DC | sed 's/.*(sl=\(0x..\))$/\1/')
        case "$current" in
          0x10)
            echo "gamer3"
            ;;
          0x0f)
            echo "gamer2"
            ;;
          0x0e)
            echo "gamer1"
            ;;
          0x0d)
            echo "racing"
            ;;
          0x0c)
            echo "rts"
            ;;
          0x0b)
            echo "fps"
            ;;
          0x00)
            echo "off"
            ;;
        esac
        exit 0
      fi
      new="$current"
      case "$1" in
        gamer3)
        new="0x10"
        ;;
        gamer2)
        new="0x0f"
        ;;
        gamer1)
        new="0x0e"
        ;;
        racing)
        new="0x0d"
        ;;
        rts)
        new="0x0c"
        ;;
        fps)
        new="0x0b"
        ;;
        off)
        new="0x00"
        ;;
      esac
      if [ "$new" != "$current" ]; then
        if [ "$display" -eq 0 ]; then
          ddcutil setvcp DC "$new"
        else
        echo ddcutil -d "$display" setvcp DC "$new"
          ddcutil -d "$display" setvcp DC "$new"
        fi
      fi
      shift
      ;;
    --display|-d)
      display="$2"
      shift
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done
