#!/usr/bin/env bash
#=================================================
# name:   chromium-start
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   17/08/2024
#=================================================
focus-or-exec "vivaldi-personal" \
    vivaldi \
        --enable-features=UseOzonePlatform \
        --ozone-platform=wayland \
        --class=vivaldi-personal \
        --profile-directory=Default \
        "$@"
