#!/usr/bin/env bash
#=================================================
# name:   netflix
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   05/07/2024
#=================================================
focus-or-exec chrome-chatgpt.com__-Default chromium --app=https://chatgpt.com --profile-directory=Default
