#!/usr/bin/env bash
#=================================================
# name:   onshape
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   22/07/2025
#=================================================
chromium --app=http://192.168.1.112 --profile-directory=Default
