#!/usr/bin/env bash
#=================================================
# name:   dji-sync
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   09/04/2025
#=================================================

hostname=$(hostname)

echo "Dji Video Sync Tool"

if [[ "$hostname" == "redeye" ]]; then
  if ping silverspoon.local -W 1 -c 1 > /dev/null 2>&1; then
    echo "> Running dji-sync on silverspoon..."
    ssh silverspoon.local -t "dji-sync"
  else
    echo "> Silverspoon not reachable, skipping sync"
  fi

  echo "> Done"
  exit 0
fi

if [[ "$hostname" == "silverspoon" ]]; then
  sdcard=false
  # DJI N3 SD Card

  if [[ -f /run/media/pbogut/SD_Card/MISC/dji_finfo.db ]] && [[ -d /run/media/pbogut/SD_Card/DCIM/100MEDIA/ ]]; then
    mkdir -p "$HOME/Videos/DjiGoggles"
    sdcard=true
    echo "> Mount point exists, syncing..."
    if rsync -av "/run/media/pbogut/SD_Card/DCIM/100MEDIA/" "$HOME/Videos/DjiGoggles/"; then
      echo "> Sync completed successfully"
      echo "> Unmounting card..."
      umount /run/media/pbogut/SD_Card
      echo "> Done"
    fi
  # DJI Mini 4K SD Card
  elif [[ -d /run/media/pbogut/disk/DCIM/100MEDIA ]]; then
    mkdir -p "$HOME/Videos/Dji"
    sdcard=true
    echo "> Mount point exists, syncing..."
    if rsync -av "/run/media/pbogut/disk/DCIM/100MEDIA/" "$HOME/Videos/Dji/"; then
      echo "> Sync completed successfully"
      echo "> Unmounting card..."
      umount /run/media/pbogut/disk
      echo "> Done"
    fi
  else
    echo "> SDa Card not mounted, skipping"
  fi

  if ping redeye.local -W 1 -c 1 > /dev/null 2>&1; then
    echo "> Syncing to redeye..."
    rsync -av "$HOME/Videos/Dji/" "redeye.local:Videos/Dji/"
    rsync -av "$HOME/Videos/DjiGoggles/" "redeye.local:Videos/DjiGoggles/"
  else
    echo "> Redeye not reachable, skipping sync"
  fi

  if $sdcard; then
    echo "> Done, SD card can be removed"
  else
    echo "> Done"
  fi

  exit 0
fi
