#!/usr/bin/env bash
#=================================================
# name:   firefox-personal
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   21/09/2024
#=================================================
firefox-developer-edition -p Personal "$@"
