#!/usr/bin/env bash
#=================================================
# name:   chromium-start
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   17/08/2024
#=================================================
focus-or-exec "vivaldi-work" vivaldi \
        --user-data-dir="$HOME/.config/vivaldi/Work/" \
        --class=vivaldi-work \
        --profile-directory=Work \
        "$@"
