#!/usr/bin/env bash
#=================================================
# name:   chromium-start
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   17/08/2024
#=================================================
swaymsg '[app_id="vivaldi-personal"] focus'
vivaldi --enable-features=UseOzonePlatform --ozone-platform=wayland --class=vivaldi-personal --profile-directory=Default "$@"
