#!/bin/bash
#=================================================
# name:   battery-save
# author: Pawel Bogut <https://pbogut.me>
# date:   25/05/2021
#=================================================
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ $1 == "on" ]]; then
  $dir/network-sync disable
fi
if [[ $1 == "off" ]]; then
  $dir/network-sync enable
fi
