#!/bin/bash

usage() {
  echo "Ussage: ${0##*/} [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  -h, --help            display this help and exit"
  echo "  -p, --profile         profile name"
  echo "  -ls, --list-profiles  list available profiles"
}

profile=""
params=()

while test $# -gt 0; do
  case "$1" in
    --help|-h)
      usage
      exit 0
      ;;
    --list-profiles|-ls)
      (
        find "$HOME/.config/opencode/" -name "*-opencode.json"
        find "$HOME/.local/share/opencode/" -name "*-auth.json"
      ) |
      sed -E 's/.*\/([^-]+)-(opencode|auth)\.json/\1/' |
      sort -u

      exit 0
      ;;
    --profile|-p)
      shift
      profile="$1"
      shift
      ;;
    *)
      params+=("$1")
      shift
      ;;
  esac
done

find_up() {
  local name="$1"
  local dir="$PWD"

  while true; do
    if [ -e "$dir/$name" ]; then
      echo "$dir/$name"
      return 0
    fi

    if [ "$dir" = "/" ]; then
      return 1
    fi

    dir="$(dirname "$dir")"
  done
}

if [ -z "$profile" ]; then
  opencode_cfg=$(find_up ".opencoderc")
  if [ -z "$opencode_cfg" ]; then
    echo "Could not find .opencoderc file"
    exit 1
  fi
  profile=$(cat "$opencode_cfg")
fi

echo "Profile: $profile"
touch "$HOME/.local/share/opencode/$profile-auth.json"
ln -f "$HOME/.local/share/opencode/$profile-auth.json" "$HOME/.local/share/opencode/auth.json"

touch "$HOME/.config/opencode/$profile-opencode.json"
ln -f "$HOME/.config/opencode/$profile-opencode.json" "$HOME/.config/opencode/opencode.json"

# if timux rename window
if [ -n "$TMUX" ]; then
  tmux rename-window "opencode[$profile]"
fi

echo opencode "${params[@]}"
opencode "${params[@]}"
