#!/usr/bin/env bash
#=================================================
# name:   terminal
# author: Pawel Bogut <https://pbogut.me>
# date:   14/06/2022
#=================================================
myargs=()
title=""
class=""
floating=false

while test $# -gt 0; do
    case "$1" in
        -e)
          shift
          ;;
        --float | -f)
            floating=true
            shift
            ;;
        --class | -c)
            class="$2"
            shift
            shift
            ;;
        --title | -t)
            title="$2"
            shift
            shift
            ;;
        *)
            myargs+=("$1")
            shift
            ;;
    esac
done

if [[ -n $title ]]; then
    export WEZTERM_TITLE="$title"
fi

if [[ $TERMINAL == "alacritty" ]]; then
    preargs=()
    if $floating; then
        class="floating"
    fi
    if [[ -n $class ]]; then
        preargs+=("--class" "Alacritty.$class")
    fi
    if [[ -n $title ]]; then
        preargs+=("--title" "$title")
    fi
    alacritty "${preargs[@]}" -e "${myargs[@]}"
elif [[ $TERMINAL == "wezterm" ]]; then
    preargs=()
    if $floating; then
        export WEZTERM_FLOATING=true
        class="floating"
    fi
    if [[ -n $class ]]; then
        preargs+=("--class" "org.wezterm.$class")
    fi
    if [[ -n $title ]]; then
        export WEZTERM_TITLE="$title"
    fi
    wezterm start "${preargs[@]}" "${myargs[@]}"
# Fall back to installed terminal
elif command -v urxvt > /dev/null; then
    urxvt -e "${myargs[@]}"
elif command -v gnome-terminal > /dev/null; then
    gnome-terminal -- "${myargs[@]}"
elif command -v urxvt > /dev/null; then
    xterm -e "${myargs[@]}"
fi
