#!/bin/bash
#=================================================
# name:   qutebrowser_ukpos.sh
# author: Pawel Bogut <http://pbogut.me>
# date:   16/01/2017
#=================================================
export PATH="$PATH:/home/$USER/.bin"
export PATH="$PATH:/home/$USER/.scripts"

url="$1"

if [[ $url =~ ^https://invidious\.pbogut\.me/watch\?v= ]]; then
  shift
  vivaldi-youtube "$url" "${@//\[\[AMPERSAND\]\]/&}" &
  exit 0
elif [[ $url =~ ^https://www\.youtube\.com/watch\?v= ]]; then
  shift
  vivaldi-youtube "$url" "${@//\[\[AMPERSAND\]\]/&}" &
  exit 0
elif [[ $url =~ ^https://open\.spotify\.com ]]; then
  vivaldi-personal "$@" &
elif [[ $url =~ ^https://.*\.zoom\.us ]]; then
  vivaldi-work "$@" &
elif [[ $url =~ ^https://rumble\.com ]]; then
  vivaldi-work "$@" &
elif [[ $url =~ ^https://gitlab\.com ]]; then
  vivaldi-work "$@" &
elif [[ $url =~ ^https://local\.* ]]; then
  vivaldi-work "$@" &
elif [[ $url =~ ^https?://*\.local ]]; then
  vivaldi-work "$@" &
else
  vivaldi-personal "$@" &
fi

exit 0;
