#!/usr/bin/env bash
#=================================================
# name:   rust-analyzer
# author: author <author_contact>
# date:   04/05/2023
#=================================================
$(rustup which rust-analyzer) "$@"
