#!/bin/bash

if [[ "$(tty)" != "/dev/tty2" ]]; then
    sudo chvt 2
    exit 0
fi

# Assume that MangoHud is not installed
MANGOAPP_FLAG=""

# Check that mangoapp is available. Set the flag if it exists,
# otherwise inform to check that MangoHud is installed and
# proceed without the flag.
if command -v mangoapp &> /dev/null;
then
    MANGOAPP_FLAG="--mangoapp"
else
    printf "[%s] [Info] 'mangoapp' is not available on your system. Check to see that MangoHud is installed.\n" "$0"
    printf "[%s] [Info] Continuing without the '--mangoapp' flag.\n" "$0"
fi

gamescope -O DP-1 --xwayland-count 2 \
    $MANGOAPP_FLAG \
    -e -- systemd-inhibit -- steam -gamepadui -steamos3 > /tmp/steam.log 2>&1

sudo chvt 1
sudo systemctl stop getty@tty2.service
