#!/usr/bin/env bash
#=================================================
# name:   executable_mirror
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   15/08/2024
#=================================================
killall wl-mirror
wl-mirror eDP-1
