#!/usr/bin/env bash
#=================================================
# name:   chezmoi-nvim
# author: author <author_contact>
# date:   16/03/2024
#=================================================
fname="$1"
encrypted=false
if [[ $fname =~ .*/chezmoi-encrypted.* ]]; then
    encrypted=true
fi

if [[ $CHEZMOI_NVIM == "open" ]]; then
    if $encrypted; then
        temp_dir="$(mktemp -d)/chezmoi-encrypted"
        mkdir -p "$temp_dir"
        if [[ $fname =~ .*\.lua ]]; then
            echo \
            '{
              "diagnostics.globals": ["vim"],
              "workspace.library": [
                "'"$HOME"'/.config/nvim/lua/",
                "'"$HOME"'/.local/share/nvim/lazy/"
              ]
            }' >> "$temp_dir/.luarc.json"
            ln -s "$HOME/.local/share/chezmoi/stylua.toml" "$temp_dir/"
            ln -s "$HOME/.local/share/chezmoi/selene.toml" "$temp_dir/"
        fi
        base_name=$(basename "$fname")
        temp_fname="$temp_dir/$base_name"
        cp "$fname" "$temp_fname"
        echo "$temp_fname"
        exit 213 # prevent chezmoi from updateing file
    else
        echo "$fname"
    fi
fi

if [[ $CHEZMOI_NVIM == "apply" ]]; then
    if $encrypted; then
      if ! diff "$fname" "$CHEZMOI_NVIM_FILE" > /dev/null 2>&1; then
          cp "$CHEZMOI_NVIM_FILE" "$fname"
      else
          exit 213 # prevent chezmoi from updateing file
      fi
    fi
fi
