#!/usr/bin/env bash
#=================================================
# name:   yt-quickupload
# author: author <author_contact>
# date:   22/07/2023
#=================================================
file="$1"
title=$(basename "$file" | yad --form --field=Title:text)
notify_id=$(dunstify -p "Uploading file ...")
if [[ $title != "" ]]; then
  youtubeuploader --title "$title" --privacy=unlisted --filename "$file" | while read -r msg; do
    dunstify -r "$notify_id" "$msg"
  done
fi
