#!/usr/bin/env bash
#=================================================
# name:   deezer
# author: author <author_contact>
# date:   08/11/2022
#=================================================
focus-or-exec "^chrome-www.deezer.com__.*" \
  chromium --app=https://www.deezer.com/en/ --profile-directory=Default
