#!/bin/bash
hyprctl dispatch "togglefloating"
json=$(hyprctl activewindow -j)
floating=$(echo "$json" | jq '.floating')
# left=$(echo $json | jq '.at[0]')
monitor="$(echo "$json" | jq '.monitor')"
screen_w=1920
width=1200
height=700
left=$(( (screen_w - width) / 2 ))
if [[ $monitor -eq 1 ]]; then
    left=$(( left + screen_w ))
fi
if [[ $floating == "true" ]]; then
    hyprctl dispatch "resizeactive exact $width $height"
    hyprctl dispatch "moveactive exact $left 200"
fi
