#!/bin/bash

if [[ "$(tty)" != "/dev/tty2" ]]; then
    sudo chvt 2
    exit 0
fi

# Assume that MangoHud is not installed
MANGOAPP_FLAG=""

# Check that mangoapp is available. Set the flag if it exists,
# otherwise inform to check that MangoHud is installed and
# proceed without the flag.
if command -v mangoapp &> /dev/null;
then
    MANGOAPP_FLAG="--mangoapp"
else
    printf "[%s] [Info] 'mangoapp' is not available on your system. Check to see that MangoHud is installed.\n" "$0"
    printf "[%s] [Info] Continuing without the '--mangoapp' flag.\n" "$0"
fi

screenrecorder() {
    while :; do
        sleep 5s;
        gpu-screen-recorder \
            -a "default_output|alsa_input.usb-SteelSeries_Arctis_Pro_Wireless-00.mono-fallback|alsa_input.usb-Telink_VR_P10_Dongle-00.mono-fallback" \
            -a "default_output" \
            -a "alsa_input.usb-SteelSeries_Arctis_Pro_Wireless-00.mono-fallback" \
            -a "alsa_input.usb-Telink_VR_P10_Dongle-00.mono-fallback" \
            -w DP-1 \
            -c mp4 \
            -o "$HOME/Videos/ShadowPlay" \
            -r 900
    done
}

screenrecorder &

gamescope -O DP-1 \
    $MANGOAPP_FLAG \
    -e \
    --sdr-gamut-wideness 1.0 \
    --xwayland-count 2 \
    --adaptive-sync \
    -- \
    systemd-inhibit \
    -- \
    steam -gamepadui -steamos3 > /tmp/steam.log 2>&1

sleep 5s;
sudo chvt 1
sudo systemctl stop getty@tty2.service
