#!/usr/bin/env bash
#=================================================
# name:   netflix
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   05/07/2024
#=================================================
chromium --app=https://www.primevideo.com/ --profile-directory=Default
