#!/usr/bin/env bash
#=================================================
# name:   chromium-start
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   17/08/2024
#=================================================
url="https://www.youtube.com/feed/history?feature=app_shortcuts"
browser="brave"
# profile="Personal"

if [[ $1 =~ ^https://www.youtube.com ]]; then
    url="$1"
fi
if [[ $1 =~ ^https://invidious.pbogut.me ]]; then
  url=${1//invidious.pbogut.me/www.youtube.com}
fi

"$browser" \
    --class=youtube \
    --app="$url" \
    "$@"

    # --profile-directory="$profile" \
