#!/usr/bin/env bash
#=================================================
# name:   hypr-sortworkspace
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   20/02/2026
#=================================================
# Make sure previous version of the script is not running
pgrep -xf "bash $0" | grep -v "$$" | xargs kill

move_to_workspace() {
  niri msg action move-window-to-workspace "$1"
}

maximized_size=1900
dynamic_workspaces='["game", "term", "3D"]'
noterm_workspaces='["web", "chat", "work", "game"]'

remove_dynamic_workspaces() {
  niri msg -j workspaces | jq --argjson names "$dynamic_workspaces" -r '.[] | select(.name != null) | select(.active_window_id == null) | select(.is_active == false) | select(.name as $name | $names | index($name)) | .name' |
    while read -r name; do
      niri msg action unset-workspace-name "$name"
    done
}
maximize_single() {
  json=$(niri msg -j focused-window)
  width=$(jq -r '.layout.window_size[0]' <<< "$json")
  ws_id=$(jq -r '.workspace_id' <<< "$json")
  # win_id=$(jq -r '.id' <<< "$json")
  echo "width: $width"
  echo "ws_id: $ws_id"
  echo "maximized_size: $maximized_size"
  if [[ $width -lt $maximized_size ]]; then
    echo "maximize"
    window_count=$(niri msg -j windows | jq --argjson ws_id "$ws_id" -r 'map(select(.workspace_id == $ws_id)) | length')
    echo "window_count: $window_count"
    if [[ $window_count -eq 1 ]]; then
      echo "maximize"
      niri msg action maximize-column
    fi
  fi
}

niri-prop -l | while read -r line; do
  app_id=$(jq -r '.app_id' <<< "$line")
  # title=$(jq -r '.title' <<< "$line")
  # win_id=$(jq -r '.window_id' <<< "$line")

  case "$app_id" in
    "Alacritty")
    current_ws=$(niri msg -j workspaces | jq --argjson names "$noterm_workspaces" -r '.[] | select(.is_focused == true) | select(.name != null) | select(.name as $name | $names | index($name)) | .name')
    if [[ $current_ws != "" ]]; then
      niri-named-workspace move term
    fi
    ;;
    "steam")
      niri-named-workspace move game -o DP-1
    ;;
    "OrcaSlicer")
      niri-named-workspace move 3D -o DP-1
    ;;
    *"-cad.onshape.com__-"*)
      niri-named-workspace move 3D -o DP-1
    ;;
    # "Alacritty.project")
    # niri-named-workspace move code -o DP-1 -c 90%
    # ;;
    # "vivaldi-personal")
    # niri-named-workspace move web -o DP-1
    # ;;
    # "ferdium")
    # niri-named-workspace move chat -o HDMI-A-1
    # ;;
    # "vivaldi-work")
    # niri-named-workspace move work -o HDMI-A-1
    # ;;
  esac
  # actions to run every "tick"
  # maximize_single
  remove_dynamic_workspaces
done
# json=$(hyprctl activewindow -j)
# class=$(echo "$json" | jq -r '.class')
# title=$(echo "$json" | jq -r '.title')
# current_ws=$(echo "$json" | jq -r '.workspace.name')

# move_and_swich() {
#   new_ws="$1"
#   if [[ "$current_ws" != "$new_ws" ]]; then
#     hyprctl dispatch movetoworkspace "name:$new_ws"
#   fi
# }


# case  "$class" in
#   "Alacritty.project")
#   move_and_swich "code"
#   ;;
#   "vivaldi-work")
#   move_and_swich "work"
#   ;;
#   "vivaldi-personal")
#   move_and_swich "web"
#   ;;
#   steam|cs2|gamescope|steam_app_*)
#   move_and_swich "steam"
#   ;;
#   "com.discordapp.Discord")
#   move_and_swich "discord"
#   ;;
#   zoom|chrome-*.zoom.us__-*)
#   move_and_swich "zoom"
#   ;;
#   brave-www.youtube.com__*|chrome-www.youtube.com__*)
#   move_and_swich "media"
#   ;;
# esac
