#!/usr/bin/env bash
#=================================================
# name:   chromium-start
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   17/08/2024
#=================================================
url="https://rumble.com/playlists/watch-history"

if [[ $1 =~ ^https://rumble.com ]]; then
    url="$1"
fi
if [[ $1 =~ ^https://www.rumble.com ]]; then
    url="$1"
fi

brave \
    --class=youtube \
    --profile-directory=Default \
    --app="$url" \
    "$@"

