#!/usr/bin/env bash
#=================================================
# name:   wezterm-list-projects
# author: author <author_contact>
# date:   04/01/2024
#=================================================
usage() {
  echo "Ussage: ${0##*/} <ACTION> [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  -h, --help     display this help and exit"
}

while test $# -gt 0; do
  case "$1" in
    --help|-h)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

project=false
if [[ $TERM == "dumb" || $TERM == "linux" ]]; then
    project=$(ls-project | wofi --dmenu -q "$1" --cache-file /dev/null)
else
    project=$(ls-project | fzf -q "$1" --height=100%)
fi


if [[ $project != "" ]]; then
    cd "$HOME/Projects/$project" || exit
    touch -h "$HOME/Projects/$project"
    wezterm-project "$PWD" "$(wezterm-status "$PWD" --title)"
    # disown
fi
