#!/bin/bash
#=================================================
# name:   docnet.sh
# author: Pawel Bogut <pbogut@ukpos.com> <http://pbogut.me>
# date:   18/05/2017
#=================================================
# if [[ ! $(id -u) == 0 ]]; then
#   echo Must be run as a user, try: sudo $(basename $0)
#   exit 1
# fi

dnsip=$(ifconfig docker0 | awk '/inet /{print $2}')
hosts="/etc/hosts"

__clear() {
  tmpfile=$(mktemp)
  cat $hosts > "$tmpfile"
  sed "/# managed by docnet $UID$/d" "$tmpfile" > $hosts
}

__disconnet() {
  tmpfile=$(mktemp)
  cat $hosts > "$tmpfile"
  sed "/#$1# managed by docnet $UID$/d" "$tmpfile" > $hosts
}

__remove() {
  if [[ -n $1 && -n $2 && -n $3 ]]; then
    tmpfile=$(mktemp)
    cat $hosts > "$tmpfile"
    sed "/$1 $2 .*#$3# managed by docnet $UID$/d" "$tmpfile" > $hosts
  fi
}

__add() {
  if [[ -n $1 && -n $2 && -n $3 ]]; then
    __remove $1 $2 $3

    padded="$(echo $1 $2 | awk '{x=$0;for(i=length;i<70;i++)x=x " ";}END{print x}')"

    echo "$padded #$3# managed by docnet $UID" | tee -a $hosts
  fi
}

__reload_dns() {
  if systemctl is-active --quiet dnsmasq.service; then
    systemctl reload dnsmasq.service
  fi
}

__allow_tailscale_web() {
  [[ $EUID == 0 ]] || return

  local subnet
  subnet=$(docker network inspect external --format '{{(index .IPAM.Config 0).Subnet}}' 2>/dev/null)
  [[ -n $subnet ]] || return

  local -a rule=(-i tailscale0 -d "$subnet" -p tcp -m multiport --dports "80,443" -j ACCEPT)
  iptables -t raw -C PREROUTING "${rule[@]}" 2>/dev/null ||
    iptables -t raw -I PREROUTING 1 "${rule[@]}"
}

__connect() {
      hash=$1
      echo $hash
      inspect=$(docker inspect $hash 2>/dev/null)
      if [[ $? == 0 ]]; then
        host=$(echo $inspect | jq '.[0].Config.Hostname' -r)
        domain=$(echo $inspect | jq '.[0].Config.Domainname' -r)
        if [[ $domain == "" ]]; then
          url=$host
        else
          url=$host.$domain
        fi

        ip=$(echo "$inspect" | jq -r '.[0].NetworkSettings.Networks.external.IPAddress // empty')
        if [[ $ip == "" ]] || [[ $ip == "null" ]]; then
          ip=$(echo $inspect | jq '.[0].NetworkSettings.IPAddress' -r)
        fi
        if [[ $ip == "" ]] || [[ $ip == "null" ]]; then
          ip=$(echo $inspect |jq '.[0].NetworkSettings.Networks | map(.IPAddress) | first' -r)
        fi
        __add $ip $url $hash

        docker inspect $hash 2>/dev/null |
          jq  '.[0].NetworkSettings.Networks | map(select(.Aliases)) | map(.Aliases[])[]' -r |
          grep '\.' | while read alias; do
            __add $ip $alias $hash
          done
      fi
}

__clear

while :; do # in case something crashes we want to restart it

  # set up already started containers
  docker ps | awk '{print $1}' | while read hash; do
    hash=$(echo $hash |sed 's,^\(.\{12\}\).*,\1,')
    __connect $hash
  done
  __allow_tailscale_web
  __reload_dns

  docker events | while read line; do
    echo $line | grep 'network \(connect\|disconnect\)' | sed 's,.*network \(disconnect\|connect\).*container=\([0-9a-z]*\)\,.*,\1 \2,' | (read action hash
      hash=$(echo $hash |sed 's,^\(.\{12\}\).*,\1,')
      if [[ $action == "connect" ]]; then
        __connect $hash
      elif [[ $action == "disconnect" ]]; then
        __disconnet $hash
      fi
      __allow_tailscale_web
      __reload_dns
    )
  done
done
