#!/usr/bin/env bash
#=================================================
# name:   chromium-start
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   17/08/2024
#=================================================
swaymsg '[app_id="vivaldi-work"] focus'
vivaldi \
    --enable-features=UseOzonePlatform \
    --ozone-platform=wayland \
    --user-data-dir="$HOME/.config/vivaldi/Work/" \
    --class=vivaldi-work \
    --profile-directory=Work \
    "$@"

