#!/usr/bin/env bash
#=================================================
# name:   disk-cleanup
# author: Pawel Bogut <pbogut@pbogut.me>
# date:   10/08/2025
#=================================================
# clean up old files from disk
trash-empty 90 -f

echo "Removing old downloads (90days+)"
find /home/pbogut/Downloads/ -type f -mtime +90 -delete
find /home/pbogut/Downloads/ -type d -empty -delete

echo "Removing old cache (90days+)"
find /home/pbogut/.cache/paru/ -mindepth 2 -maxdepth 2 -type d -mtime +90 -exec rm -fr {} \;
find /home/pbogut/.cache/paru/ -mindepth 2 -maxdepth 2 -type d -empty -delete

echo "Removing electron cache (too big, really)"
rm -fr /home/pbogut/.cache/paru/clone/electron* > /dev/null 2>&1

if [[ -d /home/pbogut/.cache/yay ]]; then
    echo "Removing yay cache"
    rm -fr /home/pbogut/.cache/yay > /dev/null 2>&1
fi
if [[ -d /home/pbogut/.cache/yarn ]]; then
    echo "Removing yarn cache"
    rm -fr /home/pbogut/.cache/yarn > /dev/null 2>&1
fi

if [[ $UID -eq 0 ]]; then
    echo "Cleaning up pacman cache"
    find /var/cache/pacman/ -type f -mtime +30 -delete
    yes | pacman -Sc
else
    echo "Not root, skipping root cleanup"
fi

echo "Removing containers closed over a year ago"
cutoff="$(date -d '1 year ago' --iso-8601=seconds)"
docker ps -a --filter "status=exited" --format '{{.ID}} {{.Names}}' |
while read -r id name; do
  finished="$(docker inspect -f '{{.State.FinishedAt}}' "$id")"
  # skip containers that never ran
  if [[ "$finished" != "0001-01-01T00:00:00Z" && "$finished" < "$cutoff" ]]; then
    printf "%s %s last_finished=%s\n" "$id" "$name" "$finished"
    docker container rm -f "$id"
  fi
done
echo "Removing unused docker images"
docker image prune -af
echo "Remove dangling unused anonymous volumes"
for v in $(docker volume ls -qf dangling=true); do
  # heuristic: anonymous volumes often look like 64 hex chars
  if [[ "$v" =~ ^[0-9a-f]{64}$ ]]; then
    kind="anonymous(looks like hash)"
    docker volume rm "$v"
  fi
done
echo "List of named volumes for review, if you dont need them, remove manually"
for v in $(docker volume ls -qf dangling=true); do
  # heuristic: anonymous volumes often look like 64 hex chars
  if [[ ! "$v" =~ ^[0-9a-f]{64}$ ]]; then
    kind="named"
    echo "$v [$kind]"
  fi
done

echo "Removing unused electron versions"
paru -Ss electron |
    grep installed |
    awk '{print $1}' |
    grep electron |
    cut -d"/" -f 2 |
    while read -r version; do
      yes | paru -R "$version" 2>/dev/null;
    done
